try {
    console.log(a)
}catch (e){
    console.log("hubo un error!")
    console.log(e)
}